### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by jushorst** [geaxgx/tello-openpose#11]
Hello. I am trying to run the OP.py file to test out openpose and keep getting an error. I have correctly installed Openpose and have tested it on my computer. I made sure BUILD_PYTHON was enabled and still am getting this error. I believe the error has to do with the file path I am using, however, I'm not sure what the correct path would be. Currently, my tello-openpose-master folder is located in the same folder as my openpose-master folder: D:\Dev. This is the error I am getting: 

D:\Dev\Python\python.exe D:/Dev/tello-openpose-master/OP.py
Error: OpenPose library could not be found. Did you enable `BUILD_PYTHON` in CMake and have this Python script in the right folder?
Traceback (most recent call last):
  File "D:/Dev/tello-openpose-master/OP.py", line 33, in <module>
    raise e
  File "D:/Dev/tello-openpose-master/OP.py", line 24, in <module>
    import pyopenpose as op
ModuleNotFoundError: No module named 'pyopenpose'

Process finished with exit code 1

Any help would be appreciated. Thank you!

**Comment by akarshgopal** [comment]
Probably late on this one, but I had the same issue (on Ubuntu). Navigating to '../openpose/build/python' and running 'make install' resolved the problem. Basically the python module for pyopenpose was not built and linked.  
Since you are working with Windows, you'll need to ensure that the folder build/x{86/64}/Release and build/bin are copied along with build/python
This is a [link](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/modules/python_module.md#exporting-python-openpose) to the official doc on the issue.
Hope it helps!
