### ISSUE TITLE
no window stream

### ISSUE THREAD

**Issue by juanmartin** [geaxgx/tello-openpose#3]
Hi, I finally managed to run tello_openpose.py only in CPU only mode on macOS High Sierra. I was not able to compile with CUDA and cudNN because of Caffe.
My terminal shows lots of these:
`Tello: 16:27:55.145:  Info: video data 378945 bytes 182.2KB/sec`
The problem is I don't see any window with the stream nor the pose recognition.
Even tried taking off with the morse code trick. Tello just stands there.
Am I missing something?
Thanks for this great project.

**Comment by geaxgx** [comment]
The lines Tello: 16:27:55.145: Info: video data 378945 bytes 182.2KB/sec are good, it means the program receives the video stream from the drone.
You don't see any window with the stream. Does it mean there is a window but it stays black, or there is no window at all ?

Can you try to use the keyboard to pilot the drone ?  Press 'tab' to for the takeoff, then press 'backspace' for landing. To know which keys you can use, search for 'controls_keypress_QWERTY' in the file 'tello_openpose.py'.

You can also start the program with the option '-l  info' or '-l debug' (more verbose) to have more messages.
So, for instance:
python tello_openpose.py -l info

PS: I am afraid that with just a CPU, you can't really use Openpose to control the tello. Have you tried openpose alone, after its installation ?

**Comment by juanmartin** [comment]
OK, tried a few things:
I understand the video is streaming ok, but there is no window, not even black. Just the terminal log which I paste down below for python2.7 and python3
```
python tello_openpose.py -l info                       1 ↵  1670  13:31:41
objc[7809]: Class CaptureDelegate is implemented in both /Users/juanmartin/.local/lib/python3.7/site-packages/cv2/cv2.cpython-37m-darwin.so (0x113d2d950) and /usr/local/opt/opencv/lib/libopencv_videoio.4.1.dylib (0x11ba31950). One of the two will be used. Which one is undefined.
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Tello: 13:31:50.931:  Info: start video thread
Tello: 13:31:50.931:  Info: send connection request (cmd="conn_req:9617")
Tello: 13:31:50.931:  Info: video receive buffer size = 524288
Tello: 13:31:50.931:  Info: state transit State::disconnected -> State::connecting
Tello: 13:31:50.932:  Info: set video encoder rate (cmd=0x20 seq=01e4)
Tello: 13:31:50.932:  Info: start video (cmd=0x25 seq=0x01e4)
Traceback (most recent call last):
  File "tello_openpose.py", line 1005, in <module>
    main(use_multiprocessing=args.multiprocess, log_level=args.log_level)
  File "tello_openpose.py", line 127, in main
    log_level=log_level, child_cnx=child_cnx)
  File "tello_openpose.py", line 236, in __init__
    self.init_drone()
  File "tello_openpose.py", line 333, in init_drone
    self.drone.subscribe(self.drone.EVENT_LOG_DATA,
AttributeError: 'Tello' object has no attribute 'EVENT_LOG_DATA'
Tello: 13:31:50.962:  Info: connected. (port=9617)
Tello: 13:31:50.963:  Info: send_time (cmd=0x46 seq=0x01e4)
Tello: 13:31:50.963:  Info: state transit State::connecting -> State::connected
Tello: 13:31:50.963:  Info: recv: ack: cmd=0x20 seq=0x0000 cc 60 00 27 b0 20 00 00 00 00 42 b9
Tello: 13:31:50.963:  Info: recv: ack: cmd=0x34 seq=0x0000 cc 60 00 27 90 34 00 00 00 00 72 a5
Tello: 13:31:50.965:  Info: recv: ack: cmd=0x20 seq=0x0000 cc 60 00 27 b0 20 00 00 00 00 42 b9
Tello: 13:31:51.014:  Info: recv: ack: cmd=0x34 seq=0x0000 cc 60 00 27 90 34 00 00 00 00 72 a5
Tello: 13:31:51.015:  Info: recv: ack: cmd=0x20 seq=0x0000 cc 60 00 27 b0 20 00 00 00 00 42 b9
Tello: 13:31:53.945:  Info: video data 389445 bytes 189.0KB/sec
Tello: 13:31:55.979:  Info: video data 381952 bytes 183.3KB/sec
	Tello: 13:31:57.980:  Info: video data 375512 bytes 183.3KB/sec
^R
Tello: 13:31:59.981:  Info: video data 377123 bytes 184.1KB/sec
^CException ignored in: <module 'threading' from '/anaconda3/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/threading.py", line 1281, in _shutdown
    t.join()
  File "/anaconda3/lib/python3.7/threading.py", line 1032, in join
    self._wait_for_tstate_lock()
  File "/anaconda3/lib/python3.7/threading.py", line 1048, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt

```
```
python3 tello_openpose.py                                ✔  1667  13:29:50
objc[7044]: Class CaptureDelegate is implemented in both /Users/juanmartin/.local/lib/python3.7/site-packages/cv2/cv2.cpython-37m-darwin.so (0x11a231950) and /usr/local/opt/opencv/lib/libopencv_videoio.4.1.dylib (0x121c47950). One of the two will be used. Which one is undefined.
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Tello: 13:30:24.681:  Info: start video thread
Tello: 13:30:24.681:  Info: send connection request (cmd="conn_req:9617")
Tello: 13:30:24.681:  Info: video receive buffer size = 524288
Tello: 13:30:24.681:  Info: state transit State::disconnected -> State::connecting
Tello: 13:30:24.681:  Info: set video encoder rate (cmd=0x20 seq=01e4)
Tello: 13:30:24.682:  Info: start video (cmd=0x25 seq=0x01e4)
Traceback (most recent call last):
  File "tello_openpose.py", line 1005, in <module>
    main(use_multiprocessing=args.multiprocess, log_level=args.log_level)
  File "tello_openpose.py", line 127, in main
    log_level=log_level, child_cnx=child_cnx)
  File "tello_openpose.py", line 236, in __init__
    self.init_drone()
  File "tello_openpose.py", line 333, in init_drone
    self.drone.subscribe(self.drone.EVENT_LOG_DATA,
AttributeError: 'Tello' object has no attribute 'EVENT_LOG_DATA'
Tello: 13:30:24.849:  Info: connected. (port=9617)
Tello: 13:30:24.849:  Info: send_time (cmd=0x46 seq=0x01e4)
Tello: 13:30:24.849:  Info: state transit State::connecting -> State::connected
Tello: 13:30:24.850:  Info: recv: ack: cmd=0x20 seq=0x0000 cc 60 00 27 b0 20 00 00 00 00 42 b9
Tello: 13:30:24.850:  Info: recv: ack: cmd=0x34 seq=0x0000 cc 60 00 27 90 34 00 00 00 00 72 a5
Tello: 13:30:24.850:  Info: recv: ack: cmd=0x20 seq=0x0000 cc 60 00 27 b0 20 00 00 00 00 42 b9
Tello: 13:30:24.891:  Info: recv: ack: cmd=0x34 seq=0x0000 cc 60 00 27 90 34 00 00 00 00 72 a5
Tello: 13:30:24.891:  Info: recv: ack: cmd=0x20 seq=0x0000 cc 60 00 27 b0 20 00 00 00 00 42 b9
Tello: 13:30:25.859:  Info: video recv: 1460 bytes 0d00 +138
Tello: 13:30:26.027:  Info: video recv: 1460 bytes 1200 +140
Tello: 13:30:26.218:  Info: video recv: 1460 bytes 1700 +164
Tello: 13:30:26.373:  Info: video recv: 1460 bytes 1c00 +136
Tello: 13:30:26.542:  Info: video recv: 1460 bytes 2100 +154
Tello: 13:30:26.723:  Info: video recv: 1460 bytes 2600 +166
Tello: 13:30:26.884:  Info: video recv: 1460 bytes 2c00 +131
Tello: 13:30:27.689:  Info: video data 404847 bytes 197.7KB/sec
Tello: 13:30:29.715:  Info: video data 380518 bytes 183.4KB/sec
Tello: 13:30:31.750:  Info: video data 381820 bytes 183.2KB/sec
Tello: 13:30:33.780:  Info: video data 381911 bytes 183.7KB/sec
Tello: 13:30:35.781:  Info: video data 375630 bytes 183.3KB/sec
Tello: 13:30:37.781:  Info: video data 379982 bytes 185.5KB/sec
	Tello: 13:30:39.782:  Info: video data 371263 bytes 181.3KB/sec
Tello: 13:30:41.783:  Info: video data 378505 bytes 184.7KB/sec
Tello: 13:30:43.784:  Info: video data 375636 bytes 183.3KB/sec
Tello: 13:30:45.813:  Info: video data 377455 bytes 181.6KB/sec loss=1
Tello: 13:30:47.814:  Info: video data 377129 bytes 184.1KB/sec
Tello: 13:30:49.814:  Info: video data 375571 bytes 183.4KB/sec
^R
Tello: 13:30:51.814:  Info: video data 377122 bytes 184.1KB/sec
Tello: 13:30:53.846:  Info: video data 378909 bytes 182.2KB/sec
	Tello: 13:30:55.846:  Info: video data 375548 bytes 183.4KB/sec
			Tello: 13:30:57.846:  Info: video data 375672 bytes 183.4KB/sec



Tello: 13:30:59.848:  Info: video data 378536 bytes 184.7KB/sec

qTello: 13:31:01.880:  Info: video data 378917 bytes 182.1KB/sec
qq
Tello: 13:31:03.880:  Info: video data 375695 bytes 183.4KB/sec
Tello: 13:31:05.880:  Info: video data 378514 bytes 184.8KB/sec
^CException ignored in: <module 'threading' from '/anaconda3/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/threading.py", line 1281, in _shutdown
    t.join()
  File "/anaconda3/lib/python3.7/threading.py", line 1032, in join
    self._wait_for_tstate_lock()
  File "/anaconda3/lib/python3.7/threading.py", line 1048, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt

```
As you can see neither tab or backspace do anything since I can only focus the terminal window.
Log shows everything fine but no window is showing the stream, therefore cannot use commands to manually pilot the Tello.

Did a test opening openpose examples and couldn't open the webcam input one (running macOS High Sierra) but could open the media input one and it was terribly slow, even to start showing the window output. So I believe CPU only mode is the problem here. Of course I knew it would be slower but thought it would at least be worth trying.
I'll keep trying to install it with CUDA and cudNN support to use the dedicated GPU. 
Is there a recommended version for CUDA and cudNN to install openpose in High Sierra?

Thanks!

**Comment by geaxgx** [comment]
From your log, the meaningful error is:
File "tello_openpose.py", line 333, in init_drone
    self.drone.subscribe(self.drone.EVENT_LOG_DATA,
AttributeError: 'Tello' object has no attribute 'EVENT_LOG_DATA'

Tello object is defined in the TelloPy package. Was there an update in TelloPy ?
No, it doesn't seem so. I can see that EVENT_LOG_DATA is still well defined at line 30 of the file https://github.com/hanyazou/TelloPy/blob/develop-0.7.0/tellopy/_internal/tello.py
So this error is very strange to me. If there is an error for "self.drone.subscribe(self.drone.EVENT_LOG_DATA,...", why there is no error for the very similar previous line in tello_openpose.py "self.drone.subscribe(self.drone.EVENT_FLIGHT_DATA,..." ?

Have you modified something in tello_openpose.py ? Because I see that self.drone.subscribe(self.drone.EVENT_LOG_DATA, is at line 333 whereas it should be at line 332.

For Openpose on High Sierra, I have no idea. Please have a look at the official repository: https://github.com/CMU-Perceptual-Computing-Lab/openpose

**Comment by juanmartin** [comment]
OK I just gave up.
Been with this all day, at some point I was able to compile openpose with gpu support but then Caffe didn't have gpu support so not even openpose examples would run.

I think I have modified tello_openpose.py because of a multiprocessing issue.
Last chance was to install Caffe with docker but I don't really understand it. I pulled the image and when ran it said that my NVIDIA driver was not detected even though I have it installed.

It's just too complicated and waay too discouraging to continue since every step has a new problem involved, and solving one thing creates a problem somewhere else. I'll just wait till I get an ubuntu or windows machine with a decent graphics card (have an old machine with Radeon graphics which are even more troublesome) to give this another go. Got sick of Mac-only problems and Ubuntu-only solutions.

Thanks for all, though.

**Comment by geaxgx** [comment]
Yeah, computer science can be very frustrating !
There is also the OpenCv version of Openpose that you can try. It only works on CPU but it should be faster than the original version of Openpose you have already tried, because OpenCV does a pretty good job in optimizing neural network inference. If you have a recent version of OpenCV (3.4.1+), you can take inspiration from : 
https://www.learnopencv.com/deep-learning-based-human-pose-estimation-using-opencv-cpp-python/
or: 
https://github.com/opencv/opencv/blob/master/samples/dnn/openpose.py 
It should give you an idea of the max speed you can get on your CPU.

**Comment by juanmartin** [comment]
Thanks! I'll give that openpose a try. I was actually thinking if I could migrate your project from openpose to another environment that doesn't depend con Caffe. Or even this: https://github.com/ildoonet/tf-pose-estimation
Still researching, maybe I find a better solution for us mac users with discrete GPU.

**Comment by duncanmix** [comment]
I have the same problem but in this case i'm using windows, I changed this
self.drone = tellopy.Tello(start_recv_thread=not self.use_multiprocessing)
to this
self.drone = tellopy.Tello(self.use_multiprocessing) 
because of a multiprocessing issue.
There is no window stream and I can't control the tello with the keyword

**Comment by geaxgx** [comment]
@duncanmix Please change instead : 
self.drone = tellopy.Tello(start_recv_thread=not self.use_multiprocessing)
to this
self.drone = tellopy.Tello()  
The self.drone = tellopy.Tello(start_recv_thread=not self.use_multiprocessing) can only work with my hacked version of TelloPy and I should modify the repository accordingly because it can't work with the official release of TelloPy. As long as, you don't use the "--multiprocessing" flag, it should work with the official release and with no argument to tellopy.Tello().

**Comment by rohitmohan7** [comment]
@geaxgx still with self.drone = tellopy.Tello() same error AttributeError: 'Tello' object has no attribute 'EVENT_LOG_DATA'

**Comment by benjaminjacobreji** [comment]
> @geaxgx still with self.drone = tellopy.Tello() same error AttributeError: 'Tello' object has no attribute 'EVENT_LOG_DATA'

Fix this by changing EVENT_LOG_DATA to EVENT_LOG in line 334 tello_openpose.py

**Comment by TejasTidke** [comment]
@geaxgx @benjaminjacobreji
**WINDOWS** Machine:
I did 
**self.drone = tellopy.Tello(start_recv_thread=not self.use_multiprocessing)**
to this
**self.drone = tellopy.Tello()**

And

changed **EVENT_LOG_DATA** to **EVENT_LOG** in line 334 tello_openpose.py

N then I was able to run the script with CPU_ONLY mode, I was even able to do the Morse_Code_Trick mentioned in your youtube Video n the drone was searching for the body, but no **openpose key point detection** was seen over my body, can u help me with this..?
I checked keypoint detection after installing openpose with python script on WINDOWS, I was able to see keypoint detection on my body though very much low fps but still it was working.

After doing the above 2 changes, though the script was working fine but was constantly getting errors in between like this, though I don't think this error has nothing to do with key-point detection:

```
Tello: 09:19:19.120:  Info: video data 378501 bytes 184.7KB/sec
Tello: 09:18:57.679: Error: recv: 'bytes' object has no attribute 'mvo'
Traceback (most recent call last):
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python36\lib\site-packages\tellopy\_internal\tello.py", line 625, in __recv_thread
    self.__process_packet(data)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python36\lib\site-packages\tellopy\_internal\tello.py", line 486, in __process_packet
    self.__publish(event=self.EVENT_LOG, data=data[9:])
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python36\lib\site-packages\tellopy\_internal\tello.py", line 154, in __publish
    dispatcher.send(event, sender=self, **args)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python36\lib\site-packages\tellopy\_internal\dispatcher.py", line 35, in send
    receiver(event=sig, **named)
  File "tello_openpose.py", line 961, in log_data_handler
    pos_x = -data.mvo.pos_x
AttributeError: 'bytes' object has no attribute 'mvo'
Tello: 09:18:59.124:  Info: video data 379016 bytes 184.9KB/sec
Tello: 09:18:59.724: Error: recv: 'bytes' object has no attribute 'mvo'
Traceback (most recent call last):
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python36\lib\site-packages\tellopy\_internal\tello.py", line 625, in __recv_thread
    self.__process_packet(data)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python36\lib\site-packages\tellopy\_internal\tello.py", line 486, in __process_packet
    self.__publish(event=self.EVENT_LOG, data=data[9:])
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python36\lib\site-packages\tellopy\_internal\tello.py", line 154, in __publish
    dispatcher.send(event, sender=self, **args)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python36\lib\site-packages\tellopy\_internal\dispatcher.py", line 35, in send
    receiver(event=sig, **named)
  File "tello_openpose.py", line 961, in log_data_handler
    pos_x = -data.mvo.pos_x
AttributeError: 'bytes' object has no attribute 'mvo'



```

**Comment by benjaminjacobreji** [comment]
Yeah so this actually a problem I faced with the models and a few installs after purging it worked. Its likely due to a messed up installation, I believe but I won't be able to confirm as reinstalling after purging fixed it for me and O didn't have this problem during my experience.
I was on a Ubuntu machine with a gtx1060 laptop and got around 20 to 25 fps, but will the optimization settings given in the doc. 
And also be sure to clean the downloaded models from cache before trying again. 
Hopefully this helps :)

**Comment by nathanbellalou** [comment]
> @geaxgx @benjaminjacobreji
> **WINDOWS** Machine:
> I did
> **self.drone = tellopy.Tello(start_recv_thread=not self.use_multiprocessing)**
> to this
> **self.drone = tellopy.Tello()**
> 
> And
> 
> changed **EVENT_LOG_DATA** to **EVENT_LOG** in line 334 tello_openpose.py
> 
> N then I was able to run the script with CPU_ONLY mode, I was even able to do the Morse_Code_Trick mentioned in your youtube Video n the drone was searching for the body, but no **openpose key point detection** was seen over my body, can u help me with this..?
> I checked keypoint detection after installing openpose with python script on WINDOWS, I was able to see keypoint detection on my body though very much low fps but still it was working.
> 
> After doing the above 2 changes, though the script was working fine but was constantly getting errors in between like this, though I don't think this error has nothing to do with key-point detection:
> 
> ```
> Tello: 09:19:19.120:  Info: video data 378501 bytes 184.7KB/sec
> Tello: 09:18:57.679: Error: recv: 'bytes' object has no attribute 'mvo'
> Traceback (most recent call last):
>   File "C:\Users\Hp\AppData\Local\Programs\Python\Python36\lib\site-packages\tellopy\_internal\tello.py", line 625, in __recv_thread
>     self.__process_packet(data)
>   File "C:\Users\Hp\AppData\Local\Programs\Python\Python36\lib\site-packages\tellopy\_internal\tello.py", line 486, in __process_packet
>     self.__publish(event=self.EVENT_LOG, data=data[9:])
>   File "C:\Users\Hp\AppData\Local\Programs\Python\Python36\lib\site-packages\tellopy\_internal\tello.py", line 154, in __publish
>     dispatcher.send(event, sender=self, **args)
>   File "C:\Users\Hp\AppData\Local\Programs\Python\Python36\lib\site-packages\tellopy\_internal\dispatcher.py", line 35, in send
>     receiver(event=sig, **named)
>   File "tello_openpose.py", line 961, in log_data_handler
>     pos_x = -data.mvo.pos_x
> AttributeError: 'bytes' object has no attribute 'mvo'
> Tello: 09:18:59.124:  Info: video data 379016 bytes 184.9KB/sec
> Tello: 09:18:59.724: Error: recv: 'bytes' object has no attribute 'mvo'
> Traceback (most recent call last):
>   File "C:\Users\Hp\AppData\Local\Programs\Python\Python36\lib\site-packages\tellopy\_internal\tello.py", line 625, in __recv_thread
>     self.__process_packet(data)
>   File "C:\Users\Hp\AppData\Local\Programs\Python\Python36\lib\site-packages\tellopy\_internal\tello.py", line 486, in __process_packet
>     self.__publish(event=self.EVENT_LOG, data=data[9:])
>   File "C:\Users\Hp\AppData\Local\Programs\Python\Python36\lib\site-packages\tellopy\_internal\tello.py", line 154, in __publish
>     dispatcher.send(event, sender=self, **args)
>   File "C:\Users\Hp\AppData\Local\Programs\Python\Python36\lib\site-packages\tellopy\_internal\dispatcher.py", line 35, in send
>     receiver(event=sig, **named)
>   File "tello_openpose.py", line 961, in log_data_handler
>     pos_x = -data.mvo.pos_x
> AttributeError: 'bytes' object has no attribute 'mvo'
> ```

@TejasTidke 
I have the same issue, did you solve it ?

**Comment by ricafort** [comment]
> > @geaxgx @benjaminjacobreji
> > **WINDOWS** Machine:
> > I did
> > **self.drone = tellopy.Tello(start_recv_thread=not self.use_multiprocessing)**
> > to this
> > **self.drone = tellopy.Tello()**
> > And
> > changed **EVENT_LOG_DATA** to **EVENT_LOG** in line 334 tello_openpose.py
> > N then I was able to run the script with CPU_ONLY mode, I was even able to do the Morse_Code_Trick mentioned in your youtube Video n the drone was searching for the body, but no **openpose key point detection** was seen over my body, can u help me with this..?
> > I checked keypoint detection after installing openpose with python script on WINDOWS, I was able to see keypoint detection on my body though very much low fps but still it was working.
> > After doing the above 2 changes, though the script was working fine but was constantly getting errors in between like this, though I don't think this error has nothing to do with key-point detection:
> > ```
> > Tello: 09:19:19.120:  Info: video data 378501 bytes 184.7KB/sec
> > Tello: 09:18:57.679: Error: recv: 'bytes' object has no attribute 'mvo'
> > Traceback (most recent call last):
> >   File "C:\Users\Hp\AppData\Local\Programs\Python\Python36\lib\site-packages\tellopy\_internal\tello.py", line 625, in __recv_thread
> >     self.__process_packet(data)
> >   File "C:\Users\Hp\AppData\Local\Programs\Python\Python36\lib\site-packages\tellopy\_internal\tello.py", line 486, in __process_packet
> >     self.__publish(event=self.EVENT_LOG, data=data[9:])
> >   File "C:\Users\Hp\AppData\Local\Programs\Python\Python36\lib\site-packages\tellopy\_internal\tello.py", line 154, in __publish
> >     dispatcher.send(event, sender=self, **args)
> >   File "C:\Users\Hp\AppData\Local\Programs\Python\Python36\lib\site-packages\tellopy\_internal\dispatcher.py", line 35, in send
> >     receiver(event=sig, **named)
> >   File "tello_openpose.py", line 961, in log_data_handler
> >     pos_x = -data.mvo.pos_x
> > AttributeError: 'bytes' object has no attribute 'mvo'
> > Tello: 09:18:59.124:  Info: video data 379016 bytes 184.9KB/sec
> > Tello: 09:18:59.724: Error: recv: 'bytes' object has no attribute 'mvo'
> > Traceback (most recent call last):
> >   File "C:\Users\Hp\AppData\Local\Programs\Python\Python36\lib\site-packages\tellopy\_internal\tello.py", line 625, in __recv_thread
> >     self.__process_packet(data)
> >   File "C:\Users\Hp\AppData\Local\Programs\Python\Python36\lib\site-packages\tellopy\_internal\tello.py", line 486, in __process_packet
> >     self.__publish(event=self.EVENT_LOG, data=data[9:])
> >   File "C:\Users\Hp\AppData\Local\Programs\Python\Python36\lib\site-packages\tellopy\_internal\tello.py", line 154, in __publish
> >     dispatcher.send(event, sender=self, **args)
> >   File "C:\Users\Hp\AppData\Local\Programs\Python\Python36\lib\site-packages\tellopy\_internal\dispatcher.py", line 35, in send
> >     receiver(event=sig, **named)
> >   File "tello_openpose.py", line 961, in log_data_handler
> >     pos_x = -data.mvo.pos_x
> > AttributeError: 'bytes' object has no attribute 'mvo'
> > ```
> 
> @TejasTidke
> I have the same issue, did you solve it ?

me too. i hope we can make this run

**Comment by ricafort** [comment]
@geaxgx . I am having this issue too. seems to be issue in tellopy. sorry for my dumb question, have you run it again recently using current tellopy? thanks

**Comment by ricafort** [comment]
> > > @geaxgx @benjaminjacobreji
> > > **WINDOWS** Machine:
> > > I did
> > > **self.drone = tellopy.Tello(start_recv_thread=not self.use_multiprocessing)**
> > > to this
> > > **self.drone = tellopy.Tello()**
> > > And
> > > changed **EVENT_LOG_DATA** to **EVENT_LOG** in line 334 tello_openpose.py
> > > N then I was able to run the script with CPU_ONLY mode, I was even able to do the Morse_Code_Trick mentioned in your youtube Video n the drone was searching for the body, but no **openpose key point detection** was seen over my body, can u help me with this..?
> > > I checked keypoint detection after installing openpose with python script on WINDOWS, I was able to see keypoint detection on my body though very much low fps but still it was working.
> > > After doing the above 2 changes, though the script was working fine but was constantly getting errors in between like this, though I don't think this error has nothing to do with key-point detection:
> > > ```
> > > Tello: 09:19:19.120:  Info: video data 378501 bytes 184.7KB/sec
> > > Tello: 09:18:57.679: Error: recv: 'bytes' object has no attribute 'mvo'
> > > Traceback (most recent call last):
> > >   File "C:\Users\Hp\AppData\Local\Programs\Python\Python36\lib\site-packages\tellopy\_internal\tello.py", line 625, in __recv_thread
> > >     self.__process_packet(data)
> > >   File "C:\Users\Hp\AppData\Local\Programs\Python\Python36\lib\site-packages\tellopy\_internal\tello.py", line 486, in __process_packet
> > >     self.__publish(event=self.EVENT_LOG, data=data[9:])
> > >   File "C:\Users\Hp\AppData\Local\Programs\Python\Python36\lib\site-packages\tellopy\_internal\tello.py", line 154, in __publish
> > >     dispatcher.send(event, sender=self, **args)
> > >   File "C:\Users\Hp\AppData\Local\Programs\Python\Python36\lib\site-packages\tellopy\_internal\dispatcher.py", line 35, in send
> > >     receiver(event=sig, **named)
> > >   File "tello_openpose.py", line 961, in log_data_handler
> > >     pos_x = -data.mvo.pos_x
> > > AttributeError: 'bytes' object has no attribute 'mvo'
> > > Tello: 09:18:59.124:  Info: video data 379016 bytes 184.9KB/sec
> > > Tello: 09:18:59.724: Error: recv: 'bytes' object has no attribute 'mvo'
> > > Traceback (most recent call last):
> > >   File "C:\Users\Hp\AppData\Local\Programs\Python\Python36\lib\site-packages\tellopy\_internal\tello.py", line 625, in __recv_thread
> > >     self.__process_packet(data)
> > >   File "C:\Users\Hp\AppData\Local\Programs\Python\Python36\lib\site-packages\tellopy\_internal\tello.py", line 486, in __process_packet
> > >     self.__publish(event=self.EVENT_LOG, data=data[9:])
> > >   File "C:\Users\Hp\AppData\Local\Programs\Python\Python36\lib\site-packages\tellopy\_internal\tello.py", line 154, in __publish
> > >     dispatcher.send(event, sender=self, **args)
> > >   File "C:\Users\Hp\AppData\Local\Programs\Python\Python36\lib\site-packages\tellopy\_internal\dispatcher.py", line 35, in send
> > >     receiver(event=sig, **named)
> > >   File "tello_openpose.py", line 961, in log_data_handler
> > >     pos_x = -data.mvo.pos_x
> > > AttributeError: 'bytes' object has no attribute 'mvo'
> > > ```
> > 
> > 
> > @TejasTidke
> > I have the same issue, did you solve it ?
> 
> me too. i hope we can make this run

I finally made the video stream run on windows for this. The issue was i am not running it as administrator in windows and firewall is blocking it. On windows, I suggest opening cmd as admin or if you are running it using pycharm or other python editor\interpreter, please run it as admin. Hope this helps and many thanks to Geaxgx for this projects. I am still getting mvo and bystream errors in the log but i can see the stream and the pose estimation. Maybe i dont have enough gpu as i am only using gtx980m and i dont have enough space and lighting in my small room to fully test it
